name: CI Development - Pull Request

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pullreq:
    name: anjing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20
