name: CI Development - Pull Request

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preparation:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun.sh
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install Dependencies
        uses: bun install --frozen-lockfile
